# Generated by Django 5.1.2 on 2024-11-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0007_alter_reference_options'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='verses',
        ),
        migrations.AddField(
            model_name='event',
            name='verses',
            field=models.ManyToManyField(to='bookdata.reference', verbose_name='verses'),
        ),
    ]
