# Generated by Django 5.1.2 on 2024-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_character'),
        ('person', '0004_character_tribe_genealogy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='character',
        ),
        migrations.AddField(
            model_name='event',
            name='characters',
            field=models.ManyToManyField(to='person.character', verbose_name='characters'),
        ),
    ]
