# Generated by Django 5.1.2 on 2024-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_character_event_characters'),
        ('person', '0004_character_tribe_genealogy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters', to='person.character', verbose_name='characters'),
        ),
    ]
