# Generated by Django 5.1.2 on 2025-01-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0008_alter_reference_options_alter_reference_book_link'),
        ('event', '0005_alter_event_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='verses',
            field=models.ManyToManyField(related_name='events', to='bookdata.reference', verbose_name='verses'),
        ),
    ]
