# Generated by Django 5.1.2 on 2024-11-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='genesis'),
            preserve_default=False,
        ),
    ]
