# Generated by Django 5.1.2 on 2024-11-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0002_book_slug'),
        ('geography', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookdata.reference')),
            ],
            options={
                'verbose_name': 'PersonReference',
                'verbose_name_plural': 'PersonReferences',
            },
        ),
        migrations.CreateModel(
            name='PlaceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookdata.reference')),
            ],
            options={
                'verbose_name': 'PlaceReference',
                'verbose_name_plural': 'PlaceReferences',
            },
        ),
    ]
