# Generated by Django 5.1.2 on 2024-11-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0003_personreference_placereference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personreference',
            name='person',
        ),
    ]
