# Generated by Django 5.1.2 on 2024-11-06 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0004_remove_personreference_person'),
        ('person', '0002_character_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='personreference',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.character'),
            preserve_default=False,
        ),
    ]
