# Generated by Django 5.1.2 on 2025-01-26 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0007_alter_reference_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('chapter', 'verse'), 'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.AlterField(
            model_name='reference',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='bookdata.book'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.ManyToManyField(related_name='links', to='bookdata.reference', verbose_name='link')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookdata.reference')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
