# Generated by Django 5.1.2 on 2025-01-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0008_alter_reference_options_alter_reference_book_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='links',
            new_name='links_references',
        ),
    ]
