# Generated by Django 5.1.2 on 2024-11-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('rio', 'Rio'), ('Región Geografica', 'Region Geografica')], max_length=50),
        ),
    ]
