# Generated by Django 5.1.2 on 2024-11-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0004_remove_personreference_person'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('feature', models.CharField(blank=True, max_length=150, null=True)),
                ('classification', models.CharField(choices=[('Varón', 'Varon'), ('Varona', 'Varona')], max_length=50)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
