# Generated by Django 5.1.2 on 2024-11-08 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '0006_delete_personreference'),
        ('person', '0002_character_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='character',
            name='feature',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.character')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookdata.reference')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
