# Generated by Django 5.1.2 on 2025-01-26 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_character_tribe_genealogy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='person.character'),
        ),
    ]
